apiVersion: v1
kind: Service
metadata:
  name: whereami
  namespace: whereami
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http 
  selector:
    app: whereami
  type: ClusterIP
