apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: whoami-ingress
  namespace: whoami
spec:
  hosts:
  - "frontend.endpoints.united-skyline-393317.cloud.goog"
  gateways:
  - asm-ingress/asm-ingressgateway
  http:
  - route:
    - destination:
        host: foo
        port:
          number: 8080
        subset: v1
      weight: 80
    - destination:
        host: foo
        port:
          number: 8080
        subset: v2
      weight: 20
