apiVersion: v1
kind: Namespace
metadata:
  name: asm-ingress
  labels:
    istio-injection: enabled
  annotations:
    config.kubernetes.io/depends-on: controlplanerevision.mesh.cloud.google.com/asm-managed-rapid
